# Use root/example as user/password credentials
version: "3.1"

services:
  db:
    image: mysql:8.4
    container_name: mysql_photoji
    command: --mysql-native-password=ON
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: photoji_dev
    ports:
      - 3306:3306
